name: CI
on:
  push:
    branches: [ extended ]
  pull_request:
    branches: [ extended ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # used to cache dependencies with a timeout
      - name: Get Date
        id: get-date
        run: |
          echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"
        shell: bash

      - name: Cache Buildozer global directory
        uses: actions/cache@v3
        with:
          path: .buildozer_global
          key: buildozer-global-${{ hashFiles('buildozer.spec') }} # Replace with your path

      - uses: actions/cache@v3
        with:
          path: .buildozer
          key: ${{ runner.os }}-${{ steps.get-date.outputs.date }}-${{ hashFiles('buildozer.spec') }}

      #- name: Build with Buildozer
      #  uses: ArtemSBulgakov/buildozer-action@v1
      #  id: buildozer
      #  with:
      #    ## command: buildozer android debug
      #    command: buildozer appclean
      #    buildozer_version: master
      #    workdir: .buildozer_global

      ###########
      - name: Install dependencies # Pythonの依存環境のインストール
        run: | #このような書き方で複数行を一気に実行することができる。
          buildozer appclean
      ###########

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}
